server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          activity-client-oidc:
            provider: spring
            client-id: activity-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: activity-client-oidc
          activity-client-authorization-code:
            provider: spring
            client-id: activity-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: activity.read
            client-name: activity-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000